# Generated by Django 2.0.5 on 2019-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='right',
            field=models.CharField(choices=[('True', 'False')], default='False', max_length=20),
        ),
    ]
