# Generated by Django 2.0.5 on 2019-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20190304_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='right',
            field=models.CharField(choices=[('True', ('False', 'True'))], default='False', max_length=20),
        ),
    ]
