# Generated by Django 2.0.5 on 2019-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20190304_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='right',
            field=models.CharField(choices=[('Choice1', 'True'), ('Choice2', 'False')], default='False', max_length=20),
        ),
    ]
