# Generated by Django 2.0.5 on 2019-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20190304_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='project',
            field=models.CharField(max_length=40),
        ),
    ]
