# Generated by Django 2.0.5 on 2019-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20190304_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='can_exec',
            field=models.CharField(choices=[('Choice1', 'True'), ('Choice2', 'False')], default='Choice2', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectright',
            name='can_read',
            field=models.CharField(choices=[('Choice1', 'True'), ('Choice2', 'False')], default='Choice2', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectright',
            name='can_write',
            field=models.CharField(choices=[('Choice1', 'True'), ('Choice2', 'False')], default='Choice2', max_length=20),
        ),
    ]
