# Generated by Django 2.0.5 on 2019-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20190305_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectright',
            name='can_exec',
            field=models.CharField(choices=[('Choice1', 'Yes'), ('Choice2', 'No')], default='Choice2', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectright',
            name='can_read',
            field=models.CharField(choices=[('Choice1', 'Yes'), ('Choice2', 'No')], default='Choice2', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectright',
            name='can_write',
            field=models.CharField(choices=[('Choice1', 'Yes'), ('Choice2', 'No')], default='Choice2', max_length=20),
        ),
    ]
